apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "gha-runner-scale-set.managerRoleBinding" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: gha-runner-scale-set-controller
    app.kubernetes.io/component: manager-role-binding
    app.kubernetes.io/version: {{ .Chart.Version }}
    actions.github.com/scale-set-name: {{ .Release.Name }}
    actions.github.com/scale-set-namespace: {{ .Release.Namespace }}
  finalizers:
    - actions.github.com/cleanup-protection
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "gha-runner-scale-set.managerRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "gha-runner-scale-set.managerServiceAccountName" . | nindent 4 }}
  namespace: {{ include "gha-runner-scale-set.managerServiceAccountNamespace" . | nindent 4 }}
