apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "gha-runner-scale-set.managerRoleName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: gha-runner-scale-set-controller
    app.kubernetes.io/component: manager-role
    app.kubernetes.io/version: {{ .Chart.Version }}
    actions.github.com/scale-set-name: {{ .Release.Name }}
    actions.github.com/scale-set-namespace: {{ .Release.Namespace }}
  finalizers:
    - actions.github.com/cleanup-protection
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  {{ $containerMode := .Values.containerMode }}
{{- if and $containerMode (eq $containerMode.type "kubernetes") }}
  - serviceaccounts
{{- end }}
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - patch
  - update
{{- if .Values.githubServerTLS }}
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
{{- end }}
