{{- $containerMode := .Values.containerMode }}
{{- if and (ne $containerMode.type "kubernetes") (not .Values.template.spec.serviceAccountName) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gha-runner-scale-set.noPermissionServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.noPermissionServiceAccount.annotations }}
  annotations:
    {{ toYaml .Values.noPermissionServiceAccount.annotations | indent 4 }}
  {{- end }}
  labels:
    {{- include "gha-runner-scale-set.labels" . | nindent 4 }}
  finalizers:
    - actions.github.com/cleanup-protection
{{- end }}
