apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: runner-scaleset
  namespace: prosper-runners
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: runner-scale-set-listener
  endpoints:
  - interval: 30s
    path: /metrics
    port: 8080
