# permissions for end users to view autoscalingrunnersets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autoscalingrunnerset-viewer-role
rules:
- apiGroups:
  - actions.summerwind.dev
  resources:
  - autoscalingrunnersets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - actions.summerwind.dev
  resources:
  - autoscalingrunnersets/status
  verbs:
  - get
