kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: actions-runner-system
  name: runner-creator
rules:
  - apiGroups: ["actions.summerwind.dev"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources: ["*"]
    verbs: ["*"]
