kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: service-admin
rules:
  - apiGroups: ["", "batch"] # "" indicates the core API group
    resources: ["*"]
    verbs: ["*"]
