name: 'E2E ARC Test Action'
description: 'Includes common arc installation, setup and test file run'

inputs:
  github-token:
    description: 'A Github PAT'
    required: true

runs:
  using: "composite"
  steps:
    - name: Helm installation
      run: |
        curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
        sudo apt-get install apt-transport-https --yes
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
        sudo apt-get update
        sudo apt-get install helm
      shell: bash
    - name: Install ARC
      run: helm install arc --namespace "arc-systems" --create-namespace oci://ghcr.io/actions/actions-runner-controller-charts/actions-runner-controller-2 --version 0.1.0
      shell: bash
    - name: Get datetime
      # We are using this value further in the runner installation to avoid runner name collision that are a risk with hard coded values.
      # A datetime including the 3 nanoseconds are a good option for this and also adds to readability and runner sorting if needed.
      run: echo "DATE_TIME=$(date +'%Y-%m-%d-%H-%M-%S-%3N')" >> $GITHUB_ENV
      shell: bash
    - name: Install runners
      run: |
          helm install "arc-runner-${{ env.DATE_TIME }}" \
          --namespace "arc-runners" \
          --create-namespace \
          --set githubConfigUrl="https://github.com/actions/actions-runner-controller" \
          --set githubConfigSecret.github_token="${{ inputs.github-token }}" \
          oci://ghcr.io/actions/actions-runner-controller-charts/auto-scaling-runner-set --version 0.1.0 \
          --debug
          kubectl get pods -A
      shell: bash
    - name: Test ARC scales pods up and down
      run: |
          export GITHUB_TOKEN="${{ inputs.github-token }}"
          export DATE_TIME="${{ env.DATE_TIME }}"
          go test ./test/e2e_arc -v
      shell: bash
