# Set actions-runner-controller settings for testing
logLevel: "-4"
imagePullSecrets:
- name:
image:
  actionsRunnerImagePullSecrets:
  - name:
githubWebhookServer:
  imagePullSecrets:
  - name:
  logLevel: "-4"
  enabled: true
  labels: {}
  replicaCount: 1
  syncPeriod: 10m
  useRunnerGroupsVisibility: true
  secret:
    enabled: true
    # create: true
    name: "github-webhook-server"
    ### GitHub Webhook Configuration
    #github_webhook_secret_token: ""
  service:
    type: NodePort
    ports:
      - port: 80
        targetPort: http
        protocol: TCP
        name: http
        nodePort: 31000
