apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "actions-runner-controller.labels" . | nindent 4 }}
  name: {{ include "actions-runner-controller.metricsServiceName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: {{ .Values.metrics.port }}
    port: 8443
    targetPort: {{ .Values.metrics.port}}
  selector:
    {{- include "actions-runner-controller.selectorLabels" . | nindent 4 }}
