{{- if or .Values.authSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: controller-manager
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{- range $k, $v := .Values.authSecret }}
  {{ $k }}: {{ $v | toString | b64enc }}
{{- end }} 
{{- end }}