apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
    name: prosper-runner-controller
    namespace: prosper-runners
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gha-rs-controller
  endpoints:
  - interval: 30s
    path: /metrics
    port: 8080
