on:
  pull_request:
    branches:
      - '**'
    paths:
      - 'runner/**'
      - .github/workflows/build-runner.yml
  push:
    branches:
      - master
    paths:
      - runner/patched/*
      - runner/Dockerfile
      - runner/entrypoint.sh
      - .github/workflows/build-runner.yml
name: Runner
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    env:
      RUNNER_VERSION: 2.273.5
      DOCKER_VERSION: 19.03.12
      DOCKERHUB_USERNAME: ${{ github.repository_owner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest

      - name: Build Container Image
        working-directory: runner
        run: |
          docker buildx build \
            --build-arg RUNNER_VERSION=${RUNNER_VERSION} \
            --build-arg DOCKER_VERSION=${DOCKER_VERSION} \
            --platform linux/amd64,linux/arm64 \
            --tag ${DOCKERHUB_USERNAME}/actions-runner:v${RUNNER_VERSION} \
            -f Dockerfile .

      - name: Push Container Image
        working-directory: runner
        run: |
          docker login -u $DOCKERHUB_USERNAME --password-stdin <<<${{ secrets.DOCKER_ACCESS_TOKEN }}
          docker push $REPO_PREFIX/actions-runner:v${RUNNER_VERSION}
          docker tag $REPO_PREFIX/actions-runner:v${RUNNER_VERSION} $REPO_PREFIX/actions-runner:latest
          docker push $REPO_PREFIX/actions-runner:latest
        if: ${{ github.event_name == 'push' }}
