on:
  pull_request:
    branches:
      - '**'
    paths:
      - 'runner/**'
      - .github/workflows/build-runner.yml
  push:
    branches:
      - master
    paths:
      - runner/patched/*
      - runner/Dockerfile
      - runner/dindrunner.Dockerfile
      - runner/entrypoint.sh
      - .github/workflows/build-runner.yml
name: Runner
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: actions-runner
            dockerfile: Dockerfile
          - name: actions-runner-dind
            dockerfile: dindrunner.Dockerfile
    env:
      RUNNER_VERSION: 2.274.2
      DOCKER_VERSION: 19.03.12
      DOCKERHUB_USERNAME: ${{ github.repository_owner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Build and Push
        uses: docker/build-push-action@v2
        if: ${{ github.event_name == 'pull_request' }}
        with:
          context: runner
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: false
          build-args: |
            RUNNER_VERSION=${RUNNER_VERSION}
            DOCKER_VERSION=${DOCKER_VERSION}
          tags: |
            ${DOCKERHUB_USERNAME}/${{ matrix.name }}:v${RUNNER_VERSION}
            ${DOCKERHUB_USERNAME}/${{ matrix.name }}:latest      

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: ${{ github.event_name == 'push' }}
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        if: ${{ github.event_name == 'push' }}
        with:
          context: runner
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            RUNNER_VERSION=${RUNNER_VERSION}
            DOCKER_VERSION=${DOCKER_VERSION}
          tags: |
            ${DOCKERHUB_USERNAME}/${{ matrix.name }}:v${RUNNER_VERSION}
            ${DOCKERHUB_USERNAME}/${{ matrix.name }}:latest
