name: Publish Controller Image

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Release
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USER }}
    steps:
      - uses: actions/checkout@v2

      - name: Set outputs
        run: |
          echo ::set-output name=version::$(cat ${GITHUB_EVENT_PATH} | jq -r '.release.tag_name')
          echo ::set-output name=sha_short::${GITHUB_SHA::7}

      - name: Install tools
        run: |
          curl -SLs https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.2.0/kubebuilder_2.2.0_linux_amd64.tar.gz -o - | tar xvzf - -C .
          sudo mv kubebuilder_2.2.0_linux_amd64 /usr/local/bin/kubebuilder
          curl -s https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh | bash
          sudo mv kustomize /usr/local/bin
          curl -SLs https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_linux_amd64.tar.gz -o - | tar xvzf - -C .
          sudo mv ghr_v0.13.0_linux_amd64/ghr /usr/local/bin/

      - name: Upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make github-release

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          ## parallelism to no of cores
          config-inline: |
            [worker.oci]
              max-parallelism = 2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build
        uses: docker/bake-action@master
        env:
          VERSION: ${{ steps.vars.outputs.version }}
          GIT_SHA: ${{ steps.vars.outputs.sha_short }}
        with:
          push: true
          targets: |
            image-all
            image-slim-all
          files: docker-bake.hcl
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
