name: Validate Runner Scripts
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'runner/**.sh'
      - 'runner/**.bash'
jobs:
  shellcheck:
    name: runner / shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: shellcheck
          path: "./runner"
          pattern: |
            *.sh
            *.bash
          # Make this consistent with `make shellsheck`
          shellcheck_flags: "--shell bash --source-path runner"
          exclude: "./.git/*"
          check_all_files_with_shebangs: "false"
          # Set this to "true" once we addressed all the shellcheck findings
          fail_on_error: "false"
