on:
  push:
    branches:
      - master
    paths-ignore:
      - "runner/**"

jobs:
  build:
    runs-on: ubuntu-latest
    name: release-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        env:
          DOCKERHUB_USERNAME: ${{ github.repository_owner }}
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${DOCKERHUB_USERNAME}/actions-runner-controller:latest 

