name: Publish Canary Image

on:
  push:
    branches:
      - master
    paths-ignore:
      - .github/workflows/runners.yml
      - .github/workflows/on-push-lint-charts.yml
      - .github/workflows/on-push-master-publish-chart.yml
      - .github/workflows/release.yml
      - .github/workflows/test-entrypoint.yml
      - "runner/**"
      - "**.md"
      - ".gitignore"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Publish Canary Image
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USER }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          ## parallelism to no of cores
          config-inline: |
            [worker.oci]
              max-parallelism = 2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build
        uses: docker/bake-action@master
        env:
          TAGS: ${{ env.DOCKERHUB_USERNAME }}/actions-runner-controller:canary
          TAGS_SLIM: ${{ env.DOCKERHUB_USERNAME }}/actions-runner-controller:canary-slim
        with:
          push: true
          targets: |
            image-all
            image-slim-all
          files: docker-bake.hcl
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
